<?xml version="1.0" standalone="yes"?>
<!DOCTYPE si_data [
<!ELEMENT display (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT unit_type (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT bit_field (mask, display)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT read_only (#PCDATA)>
<!ELEMENT post_name (#PCDATA)>
<!ELEMENT pull_down (value, display)>
<!ELEMENT parameter (post_name, display, value, min, max, unit_type, (units | step | bit_field | pull_down+)?)>
<!ELEMENT list (display, read_only?, parameter+)>
<!ELEMENT si_data (list+)>
]><si_data><list><display>Factory</display><read_only>1</read_only>
<parameter><post_name>FACTORY 0</post_name><display>Instrument Model</display><value>1400</value><min>1400</min><max>1499</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 1</post_name><display>Instrument SN</display><value>999999999</value><min>0</min><max>4294967295</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 2</post_name><display>Hardware Part Number</display><value>0</value><min>0</min><max>4294967295</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 3</post_name><display>Hardware Revision</display><value>0</value><min>0</min><max>4294967295</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 4</post_name><display>Software Part Number</display><value>0</value><min>0</min><max>4294967295</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 5</post_name><display>Software Revision</display><value>0</value><min>0</min><max>4294967295</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 6</post_name><display>Camera De-interlace</display><value>2</value><min>0</min><max>2</max><unit_type>9</unit_type><pull_down><value>1</value><display>Hardware</display></pull_down><pull_down><value>2</value><display>Serial Register Hardware</display></pull_down></parameter>
<parameter><post_name>FACTORY 7</post_name><display>De-interlace Order</display><value>2</value><min>0</min><max>3</max><unit_type>8</unit_type><pull_down><value>0</value><display>Port List</display></pull_down><pull_down><value>1</value><display>CCD Increments First</display></pull_down><pull_down><value>2</value><display>CCD Increments Last</display></pull_down></parameter>
<parameter><post_name>FACTORY 8</post_name><display>SREG 0 De-interlace Position</display><value>0</value><min>0</min><max>1</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 9</post_name><display>SREG 1 De-interlace Position</display><value>1</value><min>0</min><max>1</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 10</post_name><display>Rectangular CCD Array</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 11</post_name><display>Rectangular Grid X</display><value>3</value><min>1</min><max>25</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 12</post_name><display>Rectangular Grid Y</display><value>3</value><min>1</min><max>25</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 13</post_name><display>Installed CCDs</display><value>16</value><min>16</min><max>16</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 14</post_name><display>Installed Ports</display><value>16</value><min>16</min><max>16</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 15</post_name><display>Two Serial Registers</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 16</post_name><display>CCD Type</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Full-Frame</display></pull_down><pull_down><value>1</value><display>Frame-Transfer</display></pull_down></parameter>
<parameter><post_name>FACTORY 17</post_name><display>Parallel Clock Regions</display><value>4</value><min>4</min><max>4</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 18</post_name><display>Parallel Pre-Masked</display><value>960</value><min>0</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 19</post_name><display>Parallel Active Pix.</display><value>1920</value><min>1</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 20</post_name><display>Parallel Post-Masked</display><value>960</value><min>0</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 21</post_name><display>Serial Pre-Masked</display><value>4</value><min>0</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 22</post_name><display>Serial Active Pix.</display><value>1920</value><min>1</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 23</post_name><display>Serial Post-Masked</display><value>0</value><min>0</min><max>8191</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 24</post_name><display>Image Area Size X</display><value>30720</value><min>0</min><max>2147483647</max><unit_type>15</unit_type></parameter>
<parameter><post_name>FACTORY 25</post_name><display>Image Area Size Y</display><value>30720</value><min>0</min><max>2147483647</max><unit_type>15</unit_type></parameter>
<parameter><post_name>FACTORY 26</post_name><display>Pixel Pipeline</display><value>1</value><min>0</min><max>15</max><unit_type>11</unit_type></parameter>
<parameter><post_name>FACTORY 27</post_name><display>VDD off</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Disable</display></pull_down><pull_down><value>1</value><display>Enable</display></pull_down></parameter>
<parameter><post_name>FACTORY 28</post_name><display>Operational Temp</display><value>2032</value><min>1632</min><max>3032</max><unit_type>3</unit_type></parameter>
<parameter><post_name>FACTORY 29</post_name><display>Operational Pressure</display><value>150</value><min>0</min><max>720000</max><unit_type>2</unit_type></parameter>
<parameter><post_name>FACTORY 30</post_name><display>Parallel Region 0 Masked</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 31</post_name><display>Parallel Region 0 Shift Cap.</display><value>2</value><min>0</min><max>3</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down><pull_down><value>2</value><display>Both</display></pull_down></parameter>
<parameter><post_name>FACTORY 32</post_name><display>Parallel Region 1 Masked</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 33</post_name><display>Parallel Region 1 Shift Cap.</display><value>2</value><min>0</min><max>3</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down><pull_down><value>2</value><display>Both</display></pull_down></parameter>
<parameter><post_name>FACTORY 34</post_name><display>Parallel Region 2 Masked</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 35</post_name><display>Parallel Region 2 Shift Cap.</display><value>2</value><min>0</min><max>3</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down><pull_down><value>2</value><display>Both</display></pull_down></parameter>
<parameter><post_name>FACTORY 36</post_name><display>Parallel Region 3 Masked</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>False</display></pull_down><pull_down><value>1</value><display>True</display></pull_down></parameter>
<parameter><post_name>FACTORY 37</post_name><display>Parallel Region 3 Shift Cap.</display><value>2</value><min>0</min><max>3</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down><pull_down><value>2</value><display>Both</display></pull_down></parameter>
<parameter><post_name>FACTORY 38</post_name><display>Port 0 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 39</post_name><display>Port 0 Map</display><value>0</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 40</post_name><display>Port 0 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 41</post_name><display>Port 1 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 42</post_name><display>Port 1 Map</display><value>1</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 43</post_name><display>Port 1 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 44</post_name><display>Port 2 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 45</post_name><display>Port 2 Map</display><value>2</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 46</post_name><display>Port 2 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 47</post_name><display>Port 3 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 48</post_name><display>Port 3 Map</display><value>3</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 49</post_name><display>Port 3 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 50</post_name><display>Port 4 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 51</post_name><display>Port 4 Map</display><value>4</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 52</post_name><display>Port 4 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 53</post_name><display>Port 5 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 54</post_name><display>Port 5 Map</display><value>5</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 55</post_name><display>Port 5 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 56</post_name><display>Port 6 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 57</post_name><display>Port 6 Map</display><value>6</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 58</post_name><display>Port 6 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 59</post_name><display>Port 7 Connect</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 60</post_name><display>Port 7 Map</display><value>7</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 61</post_name><display>Port 7 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 62</post_name><display>Port 8 Connect</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 63</post_name><display>Port 8 Map</display><value>8</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 64</post_name><display>Port 8 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 65</post_name><display>Port 9 Connect</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 66</post_name><display>Port 9 Map</display><value>9</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 67</post_name><display>Port 9 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 68</post_name><display>Port 10 Connect</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 69</post_name><display>Port 10 Map</display><value>10</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 70</post_name><display>Port 10 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 71</post_name><display>Port 11 Connect</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>
<parameter><post_name>FACTORY 72</post_name><display>Port 11 Map</display><value>11</value><min>0</min><max>16</max><unit_type>8</unit_type><pull_down><value>0</value><display>ADC0</display></pull_down><pull_down><value>1</value><display>ADC1</display></pull_down><pull_down><value>2</value><display>ADC2</display></pull_down><pull_down><value>3</value><display>ADC3</display></pull_down><pull_down><value>4</value><display>ADC4</display></pull_down><pull_down><value>5</value><display>ADC5</display></pull_down><pull_down><value>6</value><display>ADC6</display></pull_down><pull_down><value>7</value><display>ADC7</display></pull_down><pull_down><value>8</value><display>ADC8</display></pull_down><pull_down><value>9</value><display>ADC9</display></pull_down><pull_down><value>10</value><display>ADC10</display></pull_down><pull_down><value>11</value><display>ADC11</display></pull_down><pull_down><value>12</value><display>ADC12</display></pull_down><pull_down><value>13</value><display>ADC13</display></pull_down><pull_down><value>14</value><display>ADC14</display></pull_down><pull_down><value>15</value><display>ADC15</display></pull_down></parameter>
<parameter><post_name>FACTORY 73</post_name><display>Port 11 Shift Direction</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Same</display></pull_down><pull_down><value>1</value><display>Reverse</display></pull_down></parameter>
<parameter><post_name>FACTORY 74</post_name><display>Port 12 Connect</display><value>1</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>SR0</display></pull_down><pull_down><value>1</value><display>SR1</display></pull_down></parameter>