<?xml version="1.0" standalone="yes"?>
<!DOCTYPE si_data [
<!ELEMENT display (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT unit_type (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT bit_field (mask, display)>
<!ELEMENT item (display, value, unit_type, (units | step | bit_field)?)>
<!ELEMENT status (item+)>
<!ELEMENT si_data (status)>
]><si_data><status>
<item><display>Controller Temperature</display><value>3225</value><unit_type>3</unit_type></item>
<item><display>Controller 0.9V Supply</display><value>904</value><unit_type>4</unit_type></item>
<item><display>Controller 1.2V Supply</display><value>1208</value><unit_type>4</unit_type></item>
<item><display>Controller 1.8V Supply</display><value>1815</value><unit_type>4</unit_type></item>
<item><display>Controller 2.5V Supply</display><value>2511</value><unit_type>4</unit_type></item>
<item><display>Slot 0 Flags</display><value>256</value><unit_type>10</unit_type><bit_field><mask>511</mask><display>Line,Frame,Integrating,Trigger Rise Armed,Trigger Rise Read,Trigger Fall Armed,Trigger Fall Read,Spare,No Sync.</display></bit_field></item>
</status></si_data>
