<?xml version="1.0" standalone="yes"?>
<!DOCTYPE si_data [
<!ELEMENT display (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT unit_type (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT bit_field (mask, display)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT read_only (#PCDATA)>
<!ELEMENT post_name (#PCDATA)>
<!ELEMENT pull_down (value, display)>
<!ELEMENT parameter (post_name, display, value, min, max, unit_type, (units | step | bit_field | pull_down+)?)>
<!ELEMENT list (display, read_only?, parameter+)>
<!ELEMENT si_data (list+)>
]><si_data><list><display>Commands</display>
<parameter><post_name>ABORT</post_name><display>Abort an exposure or readout.</display><value>0</value><min>0</min><max>0</max><unit_type>11</unit_type></parameter>
<parameter><post_name>ACQUIRE</post_name><display>Acquire an image.</display><value>0</value><min>0</min><max>7</max><unit_type>8</unit_type><pull_down><value>0</value><display>Test</display></pull_down><pull_down><value>1</value><display>Light</display></pull_down><pull_down><value>2</value><display>Dark</display></pull_down><pull_down><value>3</value><display>Triggered</display></pull_down><pull_down><value>4</value><display>Linearity</display></pull_down><pull_down><value>5</value><display>TDI ext. pacing</display></pull_down><pull_down><value>6</value><display>TDI int. pacing</display></pull_down></parameter>
<parameter><post_name>COOLER</post_name><display>Get/set the cooler enable flag.</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Off</display></pull_down><pull_down><value>1</value><display>On</display></pull_down></parameter>
<parameter><post_name>MODEDEL</post_name><display>Delete the mode at [INDEX].</display><value>0</value><min>0</min><max>15</max><unit_type>11</unit_type></parameter>
<parameter><post_name>MODEGET</post_name><display>Read the control table from [INDEX].</display><value>0</value><min>0</min><max>15</max><unit_type>11</unit_type></parameter>
<parameter><post_name>MODESET</post_name><display>Save the control table to [INDEX].</display><value>0</value><min>0</min><max>15</max><unit_type>11</unit_type></parameter>
<parameter><post_name>MS_LEFT</post_name><display>Display the remaining exposure milliseconds.</display><value>0</value><min>0</min><max>0</max><unit_type>11</unit_type></parameter>
<parameter><post_name>SHUTTER</post_name><display>Get/set the shutter open flag.</display><value>0</value><min>0</min><max>2</max><unit_type>8</unit_type><pull_down><value>0</value><display>Close</display></pull_down><pull_down><value>1</value><display>Open</display></pull_down></parameter>
<parameter><post_name>SUGET</post_name><display>Read the setup table from flash.</display><value>0</value><min>0</min><max>0</max><unit_type>11</unit_type></parameter>
<parameter><post_name>SUSET</post_name><display>Save the setup table to flash.</display><value>0</value><min>0</min><max>0</max><unit_type>11</unit_type></parameter>
<parameter><post_name>SYSRST</post_name><display>Initiate a system reset.</display><value>0</value><min>0</min><max>0</max><unit_type>11</unit_type></parameter>
</list></si_data>
